# Generated by Django 4.2.16 on 2026-02-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("pinger", "0023_add_more_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordwebhook",
            name="region_filter",
            field=models.ManyToManyField(
                blank=True, related_name="region_filters", to="eve_sde.region"
            ),
        ),
    ]
