# Generated by Aaron on 2022-01-03

from django.db import migrations


def add_ping_types(apps, schema_editor):
    PingType = apps.get_model('pinger', 'PingType')

    PingType.objects.create(name="HR: Character Left Corp",
                            class_tag="CharLeftCorpMsg")
    PingType.objects.create(name="HR: Char Application Rejected",
                            class_tag="CharAppAcceptMsg")
    PingType.objects.create(name="HR: Application Withdrawn",
                            class_tag="CharAppWithdrawMsg")



class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0024_alter_discordwebhook_region_filter'),
    ]

    operations = [
        migrations.RunPython(add_ping_types)
    ]
