# Generated by Aaron on 2022-01-03

from django.db import migrations


def add_ping_types(apps, schema_editor):
    PingType = apps.get_model('pinger', 'PingType')

    PingType.objects.create(name="Starbase: Starbase Low on Resources",
                            class_tag="TowerResourceAlertMsg")


class Migration(migrations.Migration):

    dependencies = [
        ('pinger', '0025_add_more_types'),
    ]

    operations = [
        migrations.RunPython(add_ping_types)
    ]
